[profile.default]
src = "contracts"
out = "artifacts"
libs = ["node_modules", "lib"]
test = "test"
script = "script"
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@reclaimprotocol/=node_modules/@reclaimprotocol/",
    "eth-gas-reporter/=node_modules/eth-gas-reporter/",
    "hardhat/=node_modules/hardhat/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options


[rpc_endpoints]
rails = "${RAILS_RPC_URL}"